### ISSUE TITLE
访问统计 相关内容缺失

### ISSUE THREAD

**Issue by d-w-x** [kratos-rebirth/ecosystem#1]
当前在诸多地方我们给出了 V3 `访问统计` 页面的链接，例 [这里](https://wiki.krt.moe/posts/from-v2-migration-guide/#%E8%AF%84%E8%AE%BA%E4%B8%8E%E7%AB%99%E7%82%B9%E7%BB%9F%E8%AE%A1)
> V3 版本同时也抽离了站点统计功能的支持，您可以在周边站点的 [访问统计](https://eco.krt.moe/categories/%E8%AE%BF%E9%97%AE%E7%BB%9F%E8%AE%A1/) 中尝试是否能找到一些您喜欢的统计工具。`

然而实际上该页面点开是 404，是不是需要暂时在其他页面将该链接下掉；或者编写一篇占位内容，表示仍在建设中或者等待您的共享云云？

**Comment by Candinya** [comment]
感谢提醒，加了个占位符偷个懒（
